services:
  php:
    build:
      context: ./php
    restart: always
    environment:
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./public:/app/public
      - ./conf/msmtp.conf:/app/msmtp.conf
      - ./conf/crontab:/app/crontab
    depends_on:
      - mariadb
      - memcache
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="" --innodb_buffer_pool_size=1G --table_definition_cache=16000 --table_open_cache=2000 --innodb_buffer_pool_instances=2
    restart: always
    environment:
      MARIADB_USER: appuser
      MARIADB_PASSWORD: AppPassw0rd
      MARIADB_DATABASE: app_db
      TZ: Europe/Moscow
    volumes:
      - ./mariadb:/var/lib/mysql
  memcache:
    image: memcached:latest
    restart: always
    command:
      - --conn-limit=1024
      - --memory-limit=32
      - --threads=4
  proftpd:
    build:
      context: ./proftpd
    restart: always
    environment:
      TZ: Europe/Moscow
      SFTP_USER: appuser
      SFTP_PASSWORD: AppUserPassword123
    ports:
      - "2022:22"