services:
  php:
    build:
      context: ./php
    restart: always
    environment:
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./public:/app/public
      - ./conf/msmtp.conf:/app/msmtp.conf
      - ./conf/crontab:/app/crontab
    depends_on:
      - mariadb
      - memcache
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="" --innodb_buffer_pool_size=1G --table_definition_cache=16000 --table_open_cache=2000 --innodb_buffer_pool_instances=2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Moscow
    volumes:
      - ./mariadb:/var/lib/mysql
  memcache:
    image: memcached:latest
    restart: always
    command:
      - --conn-limit=1024
      - --memory-limit=32
      - --threads=4
  sftpgo:
    image: drakkan/sftpgo
    restart: always
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./public:/app/public
      - ./conf/crontab:/app/crontab
      - ./conf/msmtp.conf:/app/msmtp.conf
      - ./conf/sftpgo.conf:/etc/sftpgo/sftpgo.conf
      - ./conf/sftpgo.users.json:/etc/sftpgo/sftpgo.users.json
    ports:
      - "2022:2022"
    depends_on:
      - php